In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("telemetry_data.csv")

In [ ]:
# Extract temperature as NumPy array
temps = df['temperature'].values

In [ ]:
# Compute: mean, std, min, max 
max_val = np.max(temps)
min_val = np.min(temps)
std_val = np.std(temps)
mean_val = np.mean(temps)
print(f"mean : {mean_val}, max: {max_val}, min: {min_val}, std: {std_val}")

mean : 25.132318909722052, max: 39.71831708240642, min: 15.300443906983784, std: 5.01091931948956

In [ ]:
# Normalize to: normalized = (temps - min_val) / (max_val - min_val)
temps_normalize = (temps - min_val) / (max_val - min_val)

In [ ]:
# Mask anomalies: mask = temps > mean + 2 * std
mask = np.argwhere(temps > (mean_val + 2 * std_val))

array([[18],
       [23],
       [43]])

In [ ]:
total_count = np.sum(mask)

np.int64(84)

In [ ]:
temps_normalize[mask] = np.nan

In [19]:
#  compute mean temperature and battery per device
device_stats = df.groupby("device_id")[['temperature', 'battery_level']].mean()
device_stats

           temperature  battery_level
device_id
1            23.826202       0.457364
2            24.626596       0.616106
3            25.965138       0.641947
4            23.549803       0.574614
5            24.148920       0.595420
6            31.581369       0.576457
7            23.283040       0.705287
8            25.219094       0.660522
9            27.451122       0.497624
10           23.614303       0.647000

In [20]:
df['temp_rolling_mean'] = df['temperature'].rolling(window=5).mean()
df.head(10)

,timestamp,device_id,temperature,battery_level,speed,temp_rolling_mean
0,2026-01-01 00:00:00,7,20.518324,0.760286,82.786900,NaN
1,2026-01-01 01:00:00,4,24.440061,0.877329,27.154292,NaN
2,2026-01-01 02:00:00,8,32.344706,0.885059,96.525183,NaN
3,2026-01-01 03:00:00,5,19.380508,0.523607,45.726516,NaN
4,2026-01-01 04:00:00,7,29.750027,0.910216,84.202308,25.286725
5,2026-01-01 05:00:00,10,33.632582,0.880743,19.438003,27.909577
6,2026-01-01 06:00:00,3,27.289425,0.948508,41.135391,28.479450
7,2026-01-01 07:00:00,7,16.578563,0.828273,69.951221,25.326221
8,2026-01-01 08:00:00,8,26.634226,0.735191,13.835309,26.776965
9,2026-01-01 09:00:00,5,24.594405,0.664549,13.274542,25.745840

In [21]:
# Filter high-risk: devices with mean temp >25°C AND any battery <0.3
high_risk = df[(df.groupby('device_id')['temperature'].mean() > 25) & (df['battery_level'] < 0.3)]
high_risk

Empty DataFrame
Columns: [timestamp, device_id, temperature, battery_level, speed, temp_rolling_mean]
Index: []